### ISSUE TITLE
Add a folder to .gitignore 

### ISSUE THREAD

**Issue by mikebrady** [ejurgensen/pair_ap#1]
Thanks for this repository, which I am using as a submodule. Would it be possible add the entry:
```
.deps
``` 
to the `.gitignore` file, please, as this folder is created when the main repository is built, and adding it to the `.gitignore` file would mean that the respository would not show up as a submodule that has been modified  when code in it has built by the main repository?

[Edit] I should say that the `.deps` folder is generated by building the main repository – which uses `autotools` – and not by building `pair_ap` itself, but it would be a great convenience to ignore the  `.deps` folder.

**Comment by ejurgensen** [comment]
Yes, of course. Also, added a few more.
